<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Purchase #{{ $purchase->id }}</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 14px;
        }
        table {
            width: 100%;
            margin-top: 20px;
            border-collapse: collapse;
        }
        td, th {
            padding: 8px;
            border: 1px solid #999;
        }
        h2 {
            text-align: center;
        }
    </style>
</head>
<body>
    <h2>Purchase Receipt</h2>

    <p><strong>Purchase ID:</strong> {{ $purchase->id }}</p>
    <p><strong>Customer:</strong> {{ $purchase->customer->name }}</p>
    <p><strong>Product:</strong> {{ $purchase->product->name }}</p>
    <p><strong>Quantity:</strong> {{ $purchase->quantity }}</p>
    <p><strong>Total:</strong> ₱{{ number_format($purchase->total, 2) }}</p>
    <p><strong>Date:</strong> {{ $purchase->created_at->format('F d, Y') }}</p>
    <p><strong>Generated by:</strong> {{ $user->name }} ({{ $user->role ?? 'Staff' }})</p>
<p><strong>Date Generated:</strong> {{ now()->format('F d, Y h:i A') }}</p>

    <p style="margin-top: 40px;">Thank you for your purchase!</p>

</body>
</html>
