<!DOCTYPE html>
<html>
<head>
    <title>Product Report</title>
</head>
<body>
    <h2>Product Report - {{ $product->name }}</h2>
    <p><strong>Description:</strong> {{ $product->description }}</p>
    <p><strong>Price:</strong> ₱{{ number_format($product->price, 2) }}</p>
    <p><strong>Stock:</strong> {{ $product->stock }}</p>
    <p><strong>Generated by:</strong> {{ $user->name }} ({{ $user->role ?? 'Staff' }})</p>
<p><strong>Date Generated:</strong> {{ now()->format('F d, Y h:i A') }}</p>

</body>
</html>
